name: CI – Windows Debug Build

on:
  workflow_dispatch:

jobs:
  build-analyze-test:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt 6.7.0 (MSVC)
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.0'
          target: desktop
          arch: win64_msvc2019_64

      - name: Install CMake
        run: |
          choco install ninja -y
          choco install cmake --version=4.0.3 -y

      - name: Configure Build Files (Application)
        run: cmake -S . -B build -G "Ninja Multi-Config" -DRUN_TESTS=OFF

      - name: Build Application (Debug)
        run: cmake --build build --config Debug --parallel

      - name: Install And Run Cppcheck
        uses: deep5050/cppcheck-action@v3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          std: c++20
          enable: all
          inconclusive: true
          platform: win64

      - name: Configure Build Files (Test)
        run: cmake -S . -B build -G "Ninja Multi-Config" -DRUN_TESTS=ON

      - name: Build Test Exe (Debug)
        run: cmake --build build --config Debug --parallel

      - name: Run Tests
        run: build\Debug\TennisDesktopApp_test.exe --gtest_color=yes

      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-debug
          path: build/Debug/**
