name: CI – Windows Debug Build

on:
  workflow_dispatch:

jobs:
  build-analyze-test:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt 6.7.0 (MSVC)
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.0'
          target: desktop
          arch: win64_msvc2019_64

      - name: Install CMake
        run: |
          choco install ninja -y
          choco install cmake --version=4.0.3 -y
          
      - name: Configure Build Files (Application)
        run: cmake -S . -B build -G "Ninja Multi-Config" -DRUN_TESTS=OFF

      - name: Build Application (Debug)
        run: cmake --build build --config Debug --parallel

      - name: Install Cppcheck
        run: |
          choco install cppcheck -y
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          refreshenv
      
      - name: Run Cppcheck (XML output)
        run: |
          cppcheck --enable=all --inconclusive --std=c++20 \
            --xml --xml-version=2 \
            inc rsc test/inc test/src 2> cppcheck-report.xml
      
      - name: Convert XML to SARIF
        uses: Flast/cppcheck-sarif@v2
        with:
          input: cppcheck-report.xml
          output: cppcheck-report.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cppcheck-report.sarif
          category: cppcheck
          
      - name: Configure Build Files (Test)
        run: cmake -S . -B build -G "Ninja Multi-Config" -DRUN_TESTS=ON

      - name: Build Test Exe (Debug)
        run: cmake --build build --config Debug --parallel

      - name: Run Tests
        run: build\Debug\TennisDesktopApp_test.exe --gtest_color=yes

      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-debug
          path: build/Debug/**
